name: expense_tracker
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.0.6+1
  http: ^0.13.5  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    

flutter_native_splash:
  color: "#32CD32"  # Background color
  image: assets/logo.png  # Path to your splash screen image
  android: true
  ios: true
